POST http://localhost:8080/token HTTP/1.1
Authorization: Basic nama:pass

###
GET http://localhost:8080
Authorization: Bearer eyJhbGciOiJSUzI1NiJ9.eyJpc3MiOiJzZWxmIiwic3ViIjoibmFtYSIsImV4cCI6MTY2NzkyMTE3NCwiaWF0IjoxNjY3OTIwNTc0LCJzY29wZSI6InJlYWQifQ.kH3LULSwUdvGHP2lAqEOvN1Ql3C9ia5BV-wABadJe4YHiHZJZwzqR0JrM2kn1p6vlLe7CG0m68lT2objt5UlRZa8dW7Zq_FxTkG7sCQtzzeXso_kH4g7LwvIdyvWNDTRRE93jAHTc8ffo6Ooem19BKaDwpFvHkNCjNAyNYbRNj8xBJ_d5X7LN0IVI0U3lHn_K0eWIGU3XawQkqlLkvCdl_ntAZ_0H1oI1X63jaVIMyu-WZALDtxYQasyAsVjkTMjzq1CR8Li0HfuKUXw6gtF89yHUylqh5ucCDhvuqspEw5DGQQb6USmzsGhlOP0n8kMeBYo4Y16vTUD2ggae2eE1g